import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import config from '../../vite.config'

/**
 * The landing page is the one file here that no other code imports, so
 * nothing else can notice when it goes stale. These are the ways it can
 * break without anyone seeing: a link that points at a path the editor no
 * longer lives on, a counter reporting to somewhere nobody reads, and that
 * counter turning up on the one page that must never carry it.
 *
 * Read as text on purpose. Parsing the pages would test a parser; what
 * matters is what ships, and what ships is these bytes -- site/ copied
 * verbatim into dist/ by the build, and index.html passed through Vite.
 */
const landing = readFileSync(new URL('../../site/index.html', import.meta.url), 'utf8')
const editor = readFileSync(new URL('../../index.html', import.meta.url), 'utf8')

/**
 * Both pages explain their arrangements in a comment beside them, and those
 * comments name the very things asserted below: the editor's says why the
 * counter is absent, and the landing page's stylesheet says which Google
 * hosts the fonts no longer come from. Matching a file as it lies would let
 * the prose satisfy the test, so every assertion of the form "this must not
 * appear" runs against the file with the comments taken out, and cannot be
 * talked out of failing. Both kinds: markup comments, and the CSS ones
 * inside <style>.
 */
const withoutComments = (html: string) =>
  html.replace(/<!--[\s\S]*?-->/g, '').replace(/\/\*[\s\S]*?\*\//g, '')
const landingCode = withoutComments(landing)
const editorCode = withoutComments(editor)

describe('the landing page', () => {
  /**
   * The editor's path is Vite's `base`, and the landing page is the only
   * way anyone reaches it. They are set in two files that have no reason
   * to be edited together, and a rename of one is invisible in the other
   * -- the deploy still goes green and every button on the home page 404s.
   * playwright.config.ts is pinned to the same value for the same reason.
   */
  it('sends people to the path the editor is actually built at', () => {
    expect(config.base).toBeTruthy()
    expect(landing).toContain(`href="${config.base}"`)
  })

  it('keeps no link to the path the project used before the rename', () => {
    expect(landing).not.toContain('FalloutShelterLayoutEditor')
  })

  it('carries the three things a crawler reads', () => {
    expect(landing).toMatch(/<title>[^<]+<\/title>/)
    expect(landing).toMatch(/<meta\s+name="description"/)
    expect(landing).toMatch(/<link rel="canonical" href="https:\/\/vault\.shamahan\.com\/"/)
  })
})

describe('the social card', () => {
  /**
   * og.png is a committed binary regenerated by hand (`node
   * tools/make-og.mjs`), so the page and the file drift apart the moment
   * the card is redrawn at another size and the meta tags are not touched.
   * Nothing would break -- the card would simply be laid out wrong by
   * whoever is previewing the link, which is the one place nobody on this
   * side ever looks.
   *
   * So the dimensions are read back out of the PNG. A PNG's IHDR chunk is
   * always first and always at the same offset: 8 bytes of signature, 4 of
   * chunk length, 4 of type, then width and height as big-endian uint32.
   */
  it('declares the size the file actually is', () => {
    const png = readFileSync(new URL('../../site/og.png', import.meta.url))
    expect(png.subarray(12, 16).toString('ascii'), 'site/og.png is not a PNG').toBe('IHDR')

    const width = png.readUInt32BE(16)
    const height = png.readUInt32BE(20)
    expect(landing).toContain(`<meta property="og:image:width" content="${width}" />`)
    expect(landing).toContain(`<meta property="og:image:height" content="${height}" />`)

    // 1.91:1 is the frame the platforms crop to; a card drawn to another
    // shape gets cut rather than letterboxed.
    expect(width / height).toBeCloseTo(1200 / 630, 3)
  })

  /**
   * A crawler fetching the card is not browsing the site and has no base to
   * resolve a relative path against, so both urls have to be absolute -- and
   * they have to point at a file that is there.
   */
  it('points at the file, absolutely', () => {
    expect(landing).toContain('content="https://vault.shamahan.com/og.png"')
    expect(landingCode).toMatch(/name="twitter:card" content="summary_large_image"/)
    expect(() => readFileSync(new URL('../../site/og.png', import.meta.url))).not.toThrow()
  })
})

describe('the visit counter', () => {
  const COUNTER = 'gc.zgo.at/count.js'

  it('is on the landing page, once', () => {
    // Split, not match: the url is mostly dots and slashes, and a regexp
    // built from it would need escaping to mean itself. Two pieces means
    // one occurrence.
    expect(landingCode.split(COUNTER)).toHaveLength(2)
  })

  /**
   * The endpoint is what makes the tag count rather than merely load. Get
   * it wrong -- a typo, someone else's instance, the snippet pasted from
   * the docs with its example host still in it -- and the page looks
   * instrumented, the script fetches fine, and the numbers go somewhere
   * nobody reads. Nothing else in the repository would notice.
   */
  it('reports to this site, not to an example in the docs', () => {
    expect(landingCode).toContain('data-goatcounter="https://shamahan.goatcounter.com/count"')
  })

  /**
   * GoatCounter's generated snippet leaves the script url
   * protocol-relative. The site is https-only, so `//` buys nothing, and on
   * the day some copy of this page is opened over http it would quietly
   * fetch a script over http too.
   */
  it('names its scheme', () => {
    expect(landingCode).not.toContain('src="//')
  })

  /**
   * And nowhere near the editor. A share link there is
   * `origin + pathname + '#' + encodeShare(vault)`, so in the editor the
   * fragment IS someone's layout -- a counter reporting the url it loaded
   * on would file a stranger's vault with a third party, silently and in
   * production only. This page has no fragment to leak, and it is the page
   * whose reach was the question. So the editor carries no third-party
   * script at all, and the second assertion is the one that keeps "add it
   * to both pages while you are there" from becoming a quiet leak.
   */
  it('stays off the editor, whose fragment may be carrying a vault', () => {
    expect(editorCode).not.toContain('goatcounter')
    expect(editorCode).not.toMatch(/<script(?![^>]*type="module")/)
  })

  /**
   * Google Analytics was here and went, taking with it the consent banner
   * it required. A gtag put back would bring cookies with it, and the
   * footer says in as many words that there are none.
   */
  it.each([
    ['the landing page', () => landingCode],
    ['the editor', () => editorCode],
  ])('loads no Google analytics through %s', (_name, page) => {
    expect(page()).not.toContain('googletagmanager.com')
    expect(page()).not.toContain('gtag(')
  })

  it('says what it does in the footer, where someone might look', () => {
    expect(landingCode).toContain('GoatCounter')
    expect(landingCode).toMatch(/no cookies/)
  })
})

describe('the typefaces', () => {
  /**
   * They used to be hotlinked from Google, which handed every visitor's IP
   * to a third party before the page had drawn anything -- on a page whose
   * footer is careful about exactly that. The counter was chosen to avoid
   * it and the fonts undid the choice, quietly, in the <head>.
   */
  it('come from this domain, not from Google', () => {
    expect(landingCode).not.toContain('fonts.googleapis.com')
    expect(landingCode).not.toContain('fonts.gstatic.com')
  })

  /**
   * And the files the rules name have to be there and have to be fonts. A
   * renamed or truncated woff2 is a silent fallback to the system font: the
   * page still renders, still passes every other test here, and simply
   * stops looking like itself. So the magic number is read back, the way
   * the social card's dimensions are.
   */
  it('name files that are there, and are fonts', () => {
    const urls = [...landingCode.matchAll(/url\((\/fonts\/[^)]+)\)/g)].map((m) => m[1])
    expect(urls.length).toBeGreaterThan(0)
    for (const url of urls) {
      const file = readFileSync(new URL('../../site' + url, import.meta.url))
      expect(file.subarray(0, 4).toString('ascii'), `${url} is not a woff2`).toBe('wOF2')
    }
  })

  /**
   * The SIL Open Font License asks that the licence travel with the font.
   * site/ is copied verbatim into the deploy, so a licence sitting here is
   * a licence served.
   */
  it.each(['Archivo-OFL.txt', 'JetBrainsMono-OFL.txt'])('ship %s', (name) => {
    const text = readFileSync(new URL('../../site/fonts/' + name, import.meta.url), 'utf8')
    expect(text).toContain('SIL OPEN FONT LICENSE')
    expect(text).toMatch(/^Copyright /)
  })
})
